"""
services/rag_service.py
-----------------------
Handles Retrieval-Augmented Generation (RAG) queries for processed meetings.

Responsibilities:
  - Isolate vector databases per meeting using dynamic in-memory overrides (monkeypatching)
  - Prevent redundant embedding operations by loading existing vector stores when available
  - Query the LangChain RAG engine to answer natural language questions about transcripts
  - Execute RAG operations inside a thread pool to prevent blocking FastAPI

This service interacts with core.rag_engine and core.vector_store.
"""

import os
import logging
import asyncio
from functools import partial

from app.services import file_service

# ── Root-level AI pipeline imports ───────────────────────────────
import core.vector_store
import core.rag_engine
from core.rag_engine import build_rag_chain, load_rag_chain, ask_question

logger = logging.getLogger(__name__)


# ─────────────────────────────────────────────────────────────────
# INTERNAL: SYNCHRONOUS RAG OPERATION
#
# Runs in a thread pool. Overrides the vector store path to target the
# specific meeting's output directory, loads/builds the database,
# and invokes the RAG chain.
# ─────────────────────────────────────────────────────────────────

def _query_rag_sync(meeting_id: str, transcript: str, question: str) -> str:
    """
    Execute the RAG query synchronously inside a thread pool.

    Args:
        meeting_id: UUID of the meeting.
        transcript: Full transcript text (used to build the DB if missing).
        question:   User's question.

    Returns:
        The response string generated by the LLM.
    """
    # ── Path Isolation ────────────────────────────────────────────
    # Dynamically point Chroma to the meeting's output folder.
    # This prevents different meetings from bleeding into the same vector store.
    meeting_output_dir = file_service.get_output_dir(meeting_id)
    isolated_chroma_dir = os.path.join(meeting_output_dir, "vector_db")

    # Override the module-level constant in core/vector_store.py
    logger.debug(f"[{meeting_id}] Redirecting Chroma directory to: {isolated_chroma_dir}")
    core.vector_store.CHROMA_DIR = isolated_chroma_dir

    # ── Load or Build Vector Store ────────────────────────────────
    # Check if the DB folder exists and contains files (e.g. chroma.sqlite3)
    db_exists = os.path.isdir(isolated_chroma_dir) and len(os.listdir(isolated_chroma_dir)) > 0

    if db_exists:
        logger.info(f"[{meeting_id}] Vector store found. Loading existing RAG chain...")
        rag_chain = load_rag_chain()
    else:
        logger.info(f"[{meeting_id}] Vector store not found. Building new RAG chain...")
        # This will call build_vector_store which uses the overridden CHROMA_DIR
        rag_chain = build_rag_chain(transcript)

    # ── Invoke Q&A ────────────────────────────────────────────────
    logger.info(f"[{meeting_id}] Querying RAG chain with question: '{question}'")
    answer = ask_question(rag_chain, question)
    logger.info(f"[{meeting_id}] RAG query complete.")

    return answer


# ─────────────────────────────────────────────────────────────────
# PUBLIC: ASYNC RAG QUERY
# ─────────────────────────────────────────────────────────────────

async def query_meeting(meeting_id: str, question: str) -> str:
    """
    Query the meeting's transcript using the RAG engine.

    Ensures the meeting has been processed, loads its transcript,
    and runs the query synchronously in a background thread.

    Args:
        meeting_id: UUID of the meeting.
        question:   Question to query the transcript with.

    Returns:
        AI-generated answer.

    Raises:
        FileNotFoundError: If the meeting has not been summarized yet.
        ValueError:        If the transcript is empty.
        RuntimeError:      If the RAG engine fails during execution.
    """
    # Validate the meeting exists and get metadata
    metadata = file_service.load_meeting_metadata(meeting_id)
    if metadata is None:
        raise FileNotFoundError(
            f"Meeting '{meeting_id}' not found or has not been processed. "
            "Please call /summarize before querying via chat."
        )

    transcript = metadata.get("transcript", "")
    if not transcript.strip():
        raise ValueError(f"No transcript content found for meeting_id '{meeting_id}'.")

    # Run the blocking RAG flow in the ThreadPoolExecutor
    loop = asyncio.get_event_loop()
    try:
        answer = await loop.run_in_executor(
            None,
            partial(_query_rag_sync, meeting_id, transcript, question)
        )
        return answer
    except Exception as e:
        logger.error(f"RAG query failed for meeting {meeting_id}: {e}")
        raise RuntimeError(f"RAG engine query error: {str(e)}")
